### PR TITLE
Fix: "Analyse on Lichess" button not loading game

### LINKED ISSUE #8: Analysis Board Stuck in Perpetual Loading State When Analyzing Chess.com Games
**Describe the bug**  
When using the lichess4chess Chrome extension on a chess.com game page, clicking the "Analyse" button opens the Lichess analysis board, but the analysis never loads. The page remains stuck on the loading screen indefinitely.

**To Reproduce**  
1. Navigate to any game on chess.com.  
2. Click the "Analyse" button from the lichess4chess extension.  
3. The Lichess analysis board opens but the game and analysis do not load.

**Expected behavior**  
The game should load completely on the Lichess analysis board, showing the full analysis.

**Actual behavior**  
The analysis board keeps loading forever without displaying the game or analysis.

**Additional context**  
- Followed all instructions in the README.md  
- Using latest version of the extension on Google Chrome  
- No errors visible in console or extension logs (please advise if logs are needed

Image

Please advise on how to proceed or if further information is required.

### PR DESCRIPTION
**Pull request by devkarx**
# Pull Request

## 📝 Description

This PR fixes the **“Analyse on Lichess”** button issue in the **lichess4chess** Chrome extension.  
Previously, clicking the button on a chess.com game page opened the Lichess analysis board but never loaded the actual game data — the page stayed stuck on the loading screen indefinitely.  

The issue was caused by outdated DOM selectors (like `.share`) that no longer exist in chess.com’s updated structure.  
This fix updates the selectors and improves game completion detection, ensuring the game now loads correctly on Lichess and analysis begins automatically.

---

### Changes Made

- Replaced obsolete `.share` selector with `[aria-label='Share']` to match the latest chess.com UI.
- Added `.game-result` selector to improve detection of finished games.
- Updated `isGameFinished()` to handle new DOM elements and reliably detect game completion.
- Updated `getCurrentGamePgn()` to correctly locate and extract the PGN from the updated “Share” button.
- Verified that “Analyse on Lichess” now loads the selected game correctly and initiates automatic analysis.
- Tested extension locally in the latest version of Chrome.

---

### Related Issues

Fixes #8 

---

## 🎯 Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Code style/formatting changes
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [ ] Build/CI changes
- [ ] Tests

---

## 📋 Checklist

- [x] Pull request describes changes clearly
- [x] Builds locally (`npm run build`)
- [x] Tested extension with latest Chrome version
- [x] No console errors observed
- [x] Verified main functionality restored

---

## 🎥 Demo

The following demonstrates the fixed behavior:
1. Open any completed game on chess.com.
2. Click **"Analyse on Lichess"**.
3. The game loads successfully on Lichess and begins automatic analysis.

---

## 📋 Additional Notes

- Tested extensively on multiple chess.com games.  
- No regressions observed in existing extension behavior.  
- All functionality now works as originally intended.

### CODE REVIEW

File: src/pages/content/gameState.ts [hunk 1]
```diff
@@ -36,7 +37,7 @@ export const detectGameState = (): GameState => {
   return GAME_STATE.NO_GAME_DETECTED;
 };
 
-export const getCurrentGamePgn = async (): Promise<string | null> => {  const shareButton = document.querySelector(".share");
+export const getCurrentGamePgn = async (): Promise<string | null> => {  const shareButton = document.querySelector("[aria-label='Share']");
```
Comment (Ryrden) [inline src/pages/content/gameState.ts:40]: Please, add a newline here.

File: package-lock.json [hunk 2]
```diff
@@ -1,12 +1,12 @@
 {
-  "name": "vite-web-extension",
-  "version": "1.4.0",
+  "name": "lichess4chess",
```
Comment (Ryrden) [inline package-lock.json:2]: Nice catch, I forgot to rename this

**Review by Ryrden — CHANGES_REQUESTED** [review]
Good PR, just some changes
